### ISSUE TITLE
Synchronize says successful and fails at the same time

### ISSUE THREAD

**Issue by GreatScott000** [TKapitan/ALRM-VSCode#16]
Trying out the synchronize function and it runs but says successful and fails at the same time.
![image](https://user-images.githubusercontent.com/4333956/118780114-a1d13100-b883-11eb-90cf-fe25fd438860.png)

Any thoughts?  I understand it is beta.  I am trying to synchronize the ALRM extension.

The failure message is:
> Synchronization of A00004 has finished with errors:
> ;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  aba92bca-e01f-4aef-827f-f8a418c67d82.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  c8ebdb39-d170-4724-b5de-2a8baf1dbaa3.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  cc8a17fc-d9e5-4fb7-b848-4ab3f013165e.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  261eb7a7-7ecf-43eb-9607-1e123670d55e.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  db3bcdf4-9267-4a5a-8a68-6be435a046b2.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  073c5e8c-a821-4b4f-82c4-acaad2b218e0.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  a4302498-2855-4f70-84ea-20f294016521.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  3c541366-1fb8-4261-8365-4026c4e53156.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  859d9c93-fe6c-43ad-92c0-d02e78b2d10d.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  2e863799-2ec7-442e-a256-b5a213d7fd5e.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  2cc410c2-13c6-4e01-a011-9dcb6b916ccd.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  26c5ac5a-ed34-4893-89cf-c13e98f801e9.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  54a3a936-ccba-4c6f-8071-fe321b944f59.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  ef9dce0d-7a01-40d7-a991-b07e6b90d39b.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  9c2d7fc3-ef99-4641-ba04-8b39f15468b4.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  3175d655-7008-4f4b-b6a7-66918e4ff084.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  b02b92b0-288a-45f3-8569-8a7c4ba94ea4.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  2f4e44fd-fd06-48eb-81e3-96885448d506.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  931ba157-d633-47d9-9ad3-d52384bc6591.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  1c4712c1-db85-4db6-8adb-d9b1d4bb1265.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  b05cf102-69c1-4db7-9fbd-57780f16a735.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  e40a0ef6-3971-4dc3-add8-6dbe29f2f191.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  06e2e23d-749f-48cc-8a9b-4606d451e1aa.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  9daa5f28-46b2-4cbb-92f1-b62895fd1cb8.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  b996e4ae-455d-4c2c-b5b3-c3422311b2f2.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  0a4a72fd-1ff1-4ea6-a6f3-94298001242c.;
> Error: There is no Extension Usage within the filter.
> 
> Filters: Extension Code: A00004, Starting Date: <=05/19/21, Ending Date: >=05/19/21|''  CorrelationId:  dd45dc71-0b8d-49e7-949b-804fbdc28061.
> 

Assignable Range info
![image](https://user-images.githubusercontent.com/4333956/118784184-b44d6980-b887-11eb-8337-b313700f9bac.png)

VSC Extension Verison: 0.4.2
![image](https://user-images.githubusercontent.com/4333956/118783082-a6e3af80-b886-11eb-86b3-efb3fdf82074.png)

**Comment by TKapitan** [comment]
Hi @GreatScott000 
The successful message is shown in error; I fix it within the next release.

About the error message: If you choose the Assignable range with "Ranges per BC instance" = true, you have to specify in which instance the extension is used (in BC: Extension List -> Usage).

**Comment by GreatScott000** [comment]
Okay, if I set it up as described it seems to work.
