### ISSUE TITLE
Error Synchronizing App

### ISSUE THREAD

**Issue by GreatScott000** [TKapitan/ALRM-VSCode#19]
Trying to synchronize an app and getting this message:
![image](https://user-images.githubusercontent.com/4333956/119322655-bd6a7c00-bc75-11eb-99fb-ae2111346123.png)

This app is a member of a multi-root project.  

The implication is that my folder has to be named "src".  Why?  Can it not just use to folder containing the app.json?

**Comment by TKapitan** [comment]
What is your dir structure? 
There are two supported dir structures (/src/ or /app/src/) based on recommended AL Project structure 

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode

**Comment by GreatScott000** [comment]
My structure is:
WorkspaceFolder
 - .alpackages folder
 - .git folder
 - App1Folder
 - App1Folder.Test
 - App2Folder
 - App2Folder.Test
 - App3Folder
 - App3Folder.Test
 - .gitignore file
 - WorkspaceFile

I would expect other users have other structures.  Why can't you just look for the app.json and assume that is the root (as it has to be) and work from there rather than assuming a fixed folder structure.  Is there a technical issue?

**Comment by TKapitan** [comment]
Sorry for the late answer. I had a lot of work on other projects...
It's not a technical problem; rather, it's by design: It's against all Microsoft recommendations and best practices to have more different projects in one workspace. The workspace should contain only App and corresponding Tests.

I also see some technical problems, such as determining which app you want to synchronise/initialise/create an object from all directories within the same workspace.

**Comment by TKapitan** [comment]
BUT!

I rechecked it, and how the whole functionality is done should also work in your workspace. To identify which folder from the workspace you are using, the system uses VS Code method workspace.getWorkspaceFolder() that returns workspace folder for the file that is open in the active text editor.

Once the system finds the workspace folder, it tries to find AL files in the src directory. Do you have the src folder inside the workspace folder you tried to synchronise?

**Comment by GreatScott000** [comment]
Sorry for the delay, been on vacation.

With the folder structure below where I have 3 app folders are you saying I need to put in SRC folder under each one?  What is the point of that?

This structure 
- WorkspaceFolder
  - .alpackages folder
  - .git folder
  - App1Folder
    App.json
    App1.Table.al
    App1.Page.al
  - App1Folder.Test
      App1Test.Codeunit.al
  - App2Folder
    App.json
    App2.Table.al
    App2.Page.al
  - App2Folder.Test
      App2Test.Codeunit.al
  - App3Folder
    App.json
    App3.Table.al
    App3.Page.al
  - App3Folder.Test
      App3Test.Codeunit.al
  .gitignore file
  WorkspaceFile

would then become this structure 
- WorkspaceFolder
  - .alpackages folder
  - .git folder
  - App1Folder
    - src
        App.json
        App1.Table.al
        App1.Page.al
  - App1Folder.Test
    - src
        App1Test.Codeunit.al
  - App2Folder
    - src
        App.json
        App2.Table.al
        App2.Page.al
  - App2Folder.Test
    - src
        App2Test.Codeunit.al
  - App3Folder
    - src
        App.json
        App3.Table.al
        App3.Page.al
  - App3Folder.Test
      App3Test.Codeunit.al
  .gitignore file
  WorkspaceFile

**Comment by GreatScott000** [comment]
I understand what you were looking for now.  Thanks.
