### ISSUE TITLE
Error Synchronizing app with dotnet.al file included

### ISSUE THREAD

**Issue by AdamSp12** [TKapitan/ALRM-VSCode#22]
Trying to synchronize an app with the command "ALRM: Synchronize"

Getting an error 
![image](https://user-images.githubusercontent.com/32476144/121711359-d0d17000-cada-11eb-8cda-db7a96a18e3f.png)

the dotnet.al file has the following structure:

dotnet
{
.
.
.
}

**Comment by TKapitan** [comment]
Cannot be replicated, CU015 extension synchronize without any errors, closing

**Comment by TKapitan** [comment]
After the investigation, it was probably caused by CR/LF mismatch based on VS Code setup. I'll add a trim function to object name identification, hope it will resolve it.
