### ISSUE TITLE
Initializing workspace question

### ISSUE THREAD

**Issue by GreatScott000** [TKapitan/ALRM-VSCode#24]
When initializing a workspace I get this prompt.
![image](https://user-images.githubusercontent.com/4333956/124266006-579fc880-db2e-11eb-9eca-0790dc4cb1a2.png)
What is expected here?  It does not seem to want to take anything I enter.

**Comment by TKapitan** [comment]
It´s probably selection of assignable ranges, but no range is specified in the BC API? I am on vacation till mid of July, I will check it and add an error message once I am back
