### ISSUE TITLE
Cannot read property 'message' of undefined error message, becouse of bad URL

### ISSUE THREAD

**Issue by molonad** [TKapitan/ALRM-VSCode#5]
![image](https://user-images.githubusercontent.com/32476124/116896424-87b51300-ac34-11eb-99a6-542836a5f894.png)

**Comment by mmu1979** [comment]
i have the same issue when i try to run the command ALARM: Initialize. My API Base URL starts with http://<IP>....

**Comment by TKapitan** [comment]
Based on info from @molonad, the error message is shown when the API URL is not accessible. I will add a better error message in the next release.
